name: postgres_recensioni

services:
  postgres:
    image: docker.io/postgres:latest
    #Per Persistenza
    # volumes:
    #   - "recensioni_db_data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recensionidb
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8089:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    profiles: [debug]
#Per Persistenza
# volumes:
#   recensioni_db_data:
#     driver: local
